version: '3.5'

services:
  hei_db:
    container_name: hei_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    image: postgres:15.2-alpine
